defmodule Postern.Catalog do
  @moduledoc """
  Loads generated PostgreSQL setting catalogs.

  Catalog files are generated by `mix postern.catalog` from live
  `pg_settings` rows. This module does not contain PostgreSQL setting
  metadata in source code.
  """

  @required_fields ~w(name vartype unit context category short_desc extra_desc min_val max_val enumvals boot_val reset_val)

  @doc """
  Loads the catalog for a PostgreSQL major version.

  The returned map contains the version and settings indexed by setting name.
  """
  @spec load(pos_integer(), keyword()) :: %{version: pos_integer(), settings: map()}
  def load(version, opts \\ []) when is_integer(version) do
    path = Path.join(catalog_dir(opts), "pg#{version}.json")

    with {:ok, json} <- File.read(path),
         {:ok, %{"settings" => settings}} <- Jason.decode(json) do
      %{
        version: version,
        settings: Map.new(settings, &{Map.fetch!(&1, "name"), &1})
      }
    else
      {:error, reason} ->
        raise "unable to load PostgreSQL #{version} catalog at #{path}: #{:file.format_error(reason)}"

      {:ok, other} ->
        raise "invalid PostgreSQL #{version} catalog at #{path}: #{inspect(other)}"
    end
  end

  @doc "Returns the PostgreSQL major versions whose catalogs are present."
  @spec versions(keyword()) :: [pos_integer()]
  def versions(opts \\ []) do
    catalog_dir(opts)
    |> Path.join("pg*.json")
    |> Path.wildcard()
    |> Enum.map(&Path.basename(&1, ".json"))
    |> Enum.flat_map(fn "pg" <> version -> parse_version(version) end)
    |> Enum.sort()
  end

  @doc "Returns the newest generated catalog version."
  @spec latest(keyword()) :: pos_integer()
  def latest(opts \\ []) do
    case versions(opts) do
      [] -> raise "no PostgreSQL catalogs found in #{catalog_dir(opts)}"
      versions -> List.last(versions)
    end
  end

  @doc "Fetches one setting row from a loaded catalog."
  @spec fetch(%{settings: map()}, String.t()) :: map() | nil
  def fetch(%{settings: settings}, name) do
    Map.get(settings, name) ||
      Enum.find_value(settings, fn {candidate, setting} ->
        if String.downcase(candidate) == String.downcase(name), do: setting
      end)
  end

  @doc "Returns the source field names expected in every generated setting row."
  @spec required_fields() :: [String.t()]
  def required_fields, do: @required_fields

  defp catalog_dir(opts) do
    Keyword.get(opts, :catalog_dir, Path.join(:code.priv_dir(:postern), "catalog"))
  end

  defp parse_version(version) do
    case Integer.parse(version) do
      {number, ""} -> [number]
      _ -> []
    end
  end
end
